In [85]:
#Extract packages
import pandas as pd
import numpy as np

In [86]:
#Extract dataset
df = pd.read_csv('https://raw.githubusercontent.com/HumayDS/A15---24-Reqemsal-data-analitika/refs/heads/main/user_activity_growth_2.csv')

In [87]:
#date – tarix
#new_users – yeni istifadəçilər
#active_users – aktiv istifadəçilər
#sessions – sessiya sayı
#acquisition_channel - müştəri hansı kanaldan gəlib
#avg_session_duration – orta sessiya müddəti (dəqiqə)
df.head()

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration
0,2025-01-01,organic,37.0,75,140.0,8.9
1,2025-01-01,paid_ads,14.0,28,53.0,7.5
2,2025-01-01,social_media,18.0,36,56.0,6.1
3,2025-01-01,referral,30.0,70,88.0,7.5
4,2025-01-01,email,12.0,33,53.0,3.8

In [88]:
#Kateqooriya analizi
df['acquisition_channel'].unique()

array(['organic', 'paid_ads', 'social_media', 'referral', 'email',
       'socialmedia'], dtype=object)

In [89]:
#KAteqoriyalari eynilesdir
df['acquisition_channel'] = df['acquisition_channel'].replace({
    'socialmedia': 'social_media'
})

In [90]:
#Müşahidələrin (rows) və dəyişənlərin (columns) sayı
df.shape

(2298, 6)

In [91]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
new_users,2276.0,64.894112,64.281802,-264.0,20.0,47.0,89.00,500.0
active_users,2298.0,180.093995,178.496002,-26.0,54.0,129.0,240.00,1414.0
sessions,2276.0,284.564587,301.986341,-42.0,84.0,196.0,375.25,4030.0
avg_session_duration,2298.0,6.852263,1.880310,3.5,5.2,6.9,8.50,10.0

In [92]:
df.isnull().sum()

date                     0
acquisition_channel      0
new_users               22
active_users             0
sessions                22
avg_session_duration     0
dtype: int64

In [93]:
df = df.fillna(df.median(numeric_only=True))

In [94]:
df.isnull().sum()

date                    0
acquisition_channel     0
new_users               0
active_users            0
sessions                0
avg_session_duration    0
dtype: int64

In [95]:
#Dublikat check
df.duplicated().sum()

np.int64(22)

In [96]:
#Dublikat check
df.groupby(['date', 'acquisition_channel']).size().reset_index(name='count').query('count > 1')

            date acquisition_channel  count
7     2025-01-02            paid_ads      2
41    2025-01-09             organic      2
57    2025-01-12            paid_ads      2
78    2025-01-16        social_media      2
97    2025-01-20        social_media      2
107   2025-01-22        social_media      2
181   2025-02-06        social_media      2
300   2025-03-02        social_media      2
514   2025-04-14        social_media      2
540   2025-04-20               email      2
588   2025-04-29        social_media      2
642   2025-05-10        social_media      2
686   2025-05-19            referral      2
796   2025-06-10        social_media      2
846   2025-06-20        social_media      2
880   2025-06-27            referral      2
945   2025-07-10            referral      2
960   2025-07-13        social_media      2
1063  2025-08-03            paid_ads      2
1080  2025-08-06        social_media      2
1105  2025-08-11        social_media      2
1134  2025-08-17        social_media      2
1147  2025-08-20            paid_ads      2
1196  2025-08-30             organic      2
1289  2025-09-17        social_media      2
1479  2025-10-25        social_media      2
1586  2025-11-16             organic      2
1706  2025-12-10             organic      2
1713  2025-12-11        social_media      2
1797  2025-12-28        social_media      2
1832  2026-01-04        social_media      2
1866  2026-01-11        social_media      2
1882  2026-01-15               email      2
1896  2026-01-17        social_media      2
2085  2026-02-24            referral      2
2167  2026-03-13               email      2

In [97]:
#Dublikatları sil
df = df.drop_duplicates()

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2276 entries, 0 to 2275
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  2276 non-null   object
 1   acquisition_channel   2276 non-null   object
 2   new_users             2276 non-null   float64
 3   active_users          2276 non-null   int64
 4   sessions              2276 non-null   float64
 5   avg_session_duration  2276 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 124.5+ KB

In [99]:
#Time formatina cevir
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2276 entries, 0 to 2275
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  2276 non-null   datetime64[ns]
 1   acquisition_channel   2276 non-null   object
 2   new_users             2276 non-null   float64
 3   active_users          2276 non-null   int64
 4   sessions              2276 non-null   float64
 5   avg_session_duration  2276 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 124.5+ KB

In [100]:
df['acquisition_channel'] = df['acquisition_channel'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2276 entries, 0 to 2275
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  2276 non-null   datetime64[ns]
 1   acquisition_channel   2276 non-null   category
 2   new_users             2276 non-null   float64
 3   active_users          2276 non-null   int64
 4   sessions              2276 non-null   float64
 5   avg_session_duration  2276 non-null   float64
dtypes: category(1), datetime64[ns](1), float64(3), int64(1)
memory usage: 109.1 KB

In [101]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
date,2276,2025-08-16 00:20:14.762741760,2025-01-01 00:00:00,2025-04-24 00:00:00,2025-08-16 00:00:00,2025-12-08 00:00:00,2026-03-31 00:00:00,NaN
new_users,2276.0,64.501318,-264.0,20.75,47.0,87.25,500.0,63.877668
active_users,2276.0,179.566344,-26.0,54.0,128.0,240.0,1414.0,178.190577
sessions,2276.0,282.848858,-42.0,85.0,196.0,370.25,4030.0,300.370738
avg_session_duration,2276.0,6.846485,3.5,5.2,6.9,8.5,10.0,1.881571

In [102]:
#Menfi deyerleri goster (new_users, acive_users, sessions)
df[(df['new_users'] < 0) | (df['active_users'] < 0) | (df['sessions'] < 0)]

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration
24,2025-01-05,email,-2.0,-5,-7.0,5.4
29,2025-01-06,email,-2.0,-6,-10.0,5.6
48,2025-01-10,referral,-3.0,-9,-14.0,8.1
119,2025-01-24,email,-1.0,-3,-5.0,7.2
134,2025-01-27,email,-2.0,-6,-10.0,4.4
...,...,...,...,...,...,...
1869,2026-01-09,email,-2.0,-5,-7.0,4.5
2044,2026-02-13,email,-9.0,-22,-40.0,9.6
2080,2026-02-21,organic,-264.0,641,196.0,4.5
2170,2026-03-11,organic,-201.0,484,663.0,4.4
2188,2026-03-14,referral,-8.0,-24,-39.0,6.8

In [103]:
#Negativ deyerleri sil
df = df[~((df['new_users'] < 0) | (df['active_users'] < 0) | (df['sessions'] < 0))]
df.head()

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration
0,2025-01-01,organic,37.0,75,140.0,8.9
1,2025-01-01,paid_ads,14.0,28,53.0,7.5
2,2025-01-01,social_media,18.0,36,56.0,6.1
3,2025-01-01,referral,30.0,70,88.0,7.5
4,2025-01-01,email,12.0,33,53.0,3.8

In [104]:
#Baslangic ve son dovre baxaq
start_date = df['date'].min()
end_date = df['date'].max()

print(f'Start Date: {start_date}')
print(f'End Date: {end_date}')

Start Date: 2025-01-01 00:00:00
End Date: 2026-03-31 00:00:00

In [105]:
#Yeni istifadecilerin sayi
df['new_users'].sum()

np.float64(148042.0)

In [106]:
#Orta session sayi
df['sessions'].mean()

np.float64(290.89745916515426)

In [107]:
#Session uzre 3 seqmente bol
df['session_quantile'] = pd.qcut(df['sessions'], q=3, labels=['low', 'medium', 'high'])
df.head()

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile
0,2025-01-01,organic,37.0,75,140.0,8.9,medium
1,2025-01-01,paid_ads,14.0,28,53.0,7.5,low
2,2025-01-01,social_media,18.0,36,56.0,6.1,low
3,2025-01-01,referral,30.0,70,88.0,7.5,low
4,2025-01-01,email,12.0,33,53.0,3.8,low

In [108]:
#Session seqmentine gore ortalama ve cem session sayi, new-users cemlerini qruplashdir
grouped_data = df.groupby('session_quantile').agg(
    sessions_sum=('sessions', 'sum'),
    sessions_mean=('sessions', 'mean'),
    new_users_sum=('new_users', 'sum')
).reset_index()
print(grouped_data)

  session_quantile  sessions_sum  sessions_mean  new_users_sum
0              low       45934.0      61.989204        12179.0
1           medium      151227.0     207.729396        38035.0
2             high      443977.0     604.050340        97828.0

/tmp/ipykernel_10612/1186376915.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_data = df.groupby('session_quantile').agg(

In [109]:
#AY ve il sutunu yarat
df['month'] =  df['date'].dt.month
df['year'] = df['date'].dt.year

In [110]:
filtered_df = df[(df['acquisition_channel'] == 'paid_ads') & (df['year'] == 2025)]
filtered_df

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile,month,year
1,2025-01-01,paid_ads,14.0,28,53.0,7.5,low,1,2025
6,2025-01-02,paid_ads,13.0,40,59.0,4.9,low,1,2025
11,2025-01-03,paid_ads,7.0,14,24.0,8.1,low,1,2025
16,2025-01-04,paid_ads,38.0,101,135.0,9.3,medium,1,2025
21,2025-01-05,paid_ads,35.0,95,160.0,5.3,medium,1,2025
...,...,...,...,...,...,...,...,...,...
1801,2025-12-27,paid_ads,58.0,136,163.0,8.4,medium,12,2025
1806,2025-12-28,paid_ads,182.0,632,879.0,4.8,high,12,2025
1811,2025-12-29,paid_ads,116.0,401,654.0,9.9,high,12,2025
1816,2025-12-30,paid_ads,73.0,171,279.0,6.5,medium,12,2025
1821,2025-12-31,paid_ads,106.0,248,337.0,9.4,high,12,2025

In [111]:
sessions_by_month = df.groupby(['year', 'month'])['sessions'].sum().reset_index()
print(sessions_by_month)

    year  month  sessions
0   2025      1   18490.0
1   2025      2   18228.0
2   2025      3   23473.0
3   2025      4   25227.0
4   2025      5   32570.0
5   2025      6   28821.0
6   2025      7   31773.0
7   2025      8   37542.0
8   2025      9   41349.0
9   2025     10   43631.0
10  2025     11   80977.0
11  2025     12   88271.0
12  2026      1   57180.0
13  2026      2   52307.0
14  2026      3   61299.0

In [112]:
#Kanal uzre celb olunmus yeni musteri
grouped_by_channel = df.groupby('acquisition_channel')['sessions'].sum().reset_index()
print(grouped_by_channel)

  acquisition_channel  sessions
0               email   68398.0
1             organic  217079.0
2            paid_ads  138574.0
3            referral   74510.0
4        social_media  142577.0

/tmp/ipykernel_10612/4084765610.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_by_channel = df.groupby('acquisition_channel')['sessions'].sum().reset_index()

In [113]:
#Outlier check
num_cols = ['new_users', 'active_users', 'sessions', 'avg_session_duration']
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

outlier_mask = (df[num_cols] < (Q1 - 2 * IQR)) | (df[num_cols] > (Q3 + 2 * IQR))

In [114]:
#Outlier check
outlier_mask.sum()

new_users               70
active_users            84
sessions                74
avg_session_duration     0
dtype: int64

In [115]:
df_outliers = df[outlier_mask.any(axis=1)]
df_outliers.head(20)

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile,month,year
63,2025-01-13,referral,42.0,135,2210.0,8.8,high,1,2025
690,2025-05-19,organic,56.0,182,2460.0,5.1,high,5,2025
1140,2025-08-17,organic,35.0,113,1680.0,4.0,high,8,2025
1148,2025-08-18,referral,29.0,65,1090.0,7.7,high,8,2025
1195,2025-08-28,organic,211.0,551,1007.0,9.3,high,8,2025
1250,2025-09-08,organic,172.0,527,991.0,8.6,high,9,2025
1361,2025-09-30,paid_ads,190.0,651,1064.0,8.1,high,9,2025
1423,2025-10-12,referral,216.0,746,914.0,5.6,high,10,2025
1430,2025-10-14,organic,176.0,588,1110.0,7.6,high,10,2025
1485,2025-10-25,organic,214.0,694,1297.0,8.0,high,10,2025
1523,2025-11-01,referral,292.0,869,1476.0,8.0,high,11,2025
1527,2025-11-02,social_media,245.0,609,788.0,9.3,high,11,2025
1530,2025-11-03,organic,253.0,662,982.0,7.9,high,11,2025
1537,2025-11-04,social_media,357.0,791,1357.0,7.4,high,11,2025
1541,2025-11-05,paid_ads,221.0,631,1156.0,6.1,high,11,2025
1542,2025-11-05,social_media,204.0,701,889.0,3.6,high,11,2025
1546,2025-11-06,paid_ads,228.0,642,1019.0,6.7,high,11,2025
1550,2025-11-07,organic,264.0,595,986.0,3.7,high,11,2025
1555,2025-11-08,organic,326.0,657,1027.0,7.4,high,11,2025
1557,2025-11-08,social_media,172.0,583,1037.0,5.6,high,11,2025

# Qayda
#Outlier 2 cür olur : Real event(silinməməlidir) , Data error (silinməlidir)
#Outlier silməzdən əvvəl səbəbini izah edə bilməlisən.
#Əgər izah edə bilmirsənsə:

##ya saxla
##ya ayrıca flag et

In [116]:
df['is_outlier'] = outlier_mask.any(axis=1)

In [117]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
date,2204,2025-08-17 22:48:07.840290304,2025-01-01 00:00:00,2025-04-27 00:00:00,2025-08-19 00:00:00,2025-12-10 00:00:00,2026-03-31 00:00:00,NaN
new_users,2204.0,67.169691,0.0,22.0,48.0,90.0,500.0,62.677628
active_users,2204.0,184.490472,0.0,60.0,132.0,243.0,1414.0,177.794751
sessions,2204.0,290.897459,0.0,91.0,200.0,380.25,4030.0,300.883213
avg_session_duration,2204.0,6.846824,3.5,5.2,6.85,8.5,10.0,1.884578
month,2204.0,5.643829,1.0,2.0,5.0,9.0,12.0,3.603184
year,2204.0,2025.201906,2025.0,2025.0,2025.0,2025.0,2026.0,0.401513

In [118]:
#Outlieri sil
df_clean = df[~outlier_mask.any(axis=1)]

In [119]:
df_clean.describe().T

,count,mean,min,25%,50%,75%,max,std
date,2095,2025-08-11 22:49:53.412887808,2025-01-01 00:00:00,2025-04-21 12:00:00,2025-08-08 00:00:00,2025-12-02 00:00:00,2026-03-31 00:00:00,NaN
new_users,2095.0,58.230072,0.0,21.0,47.0,83.0,226.0,46.992872
active_users,2095.0,157.88926,0.0,56.0,124.0,223.0,601.0,129.517952
sessions,2095.0,245.285919,0.0,87.5,192.0,345.0,953.0,205.236172
avg_session_duration,2095.0,6.848067,3.5,5.25,6.8,8.5,10.0,1.884331
month,2095.0,5.486874,1.0,2.0,5.0,8.0,12.0,3.49576
year,2095.0,2025.198568,2025.0,2025.0,2025.0,2025.0,2026.0,0.399017

In [120]:
new_users_by_year_month = df.groupby(['year', 'month'])['new_users'].sum()
print(new_users_by_year_month)

year  month
2025  1         3952.0
      2         4250.0
      3         5434.0
      4         5799.0
      5         7043.0
      6         6776.0
      7         7732.0
      8         8242.0
      9         9520.0
      10       10670.0
      11       18926.0
      12       20662.0
2026  1        12516.0
      2        12203.0
      3        14317.0
Name: new_users, dtype: float64

In [121]:
#Kanal uzre analitika
channel_users = df.groupby('acquisition_channel')['active_users'].sum().reset_index()
channel_users = channel_users.sort_values(by='active_users', ascending=False)
channel_users

/tmp/ipykernel_10612/2843591222.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  channel_users = df.groupby('acquisition_channel')['active_users'].sum().reset_index()

  acquisition_channel  active_users
1             organic        135728
4        social_media         90999
2            paid_ads         90191
3            referral         46080
0               email         43619

In [122]:
new_users_by_year_month = df.groupby(['year', 'month'])['new_users'].sum()
print(new_users_by_year_month)

year  month
2025  1         3952.0
      2         4250.0
      3         5434.0
      4         5799.0
      5         7043.0
      6         6776.0
      7         7732.0
      8         8242.0
      9         9520.0
      10       10670.0
      11       18926.0
      12       20662.0
2026  1        12516.0
      2        12203.0
      3        14317.0
Name: new_users, dtype: float64

In [123]:
df.head()

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile,month,year,is_outlier
0,2025-01-01,organic,37.0,75,140.0,8.9,medium,1,2025,False
1,2025-01-01,paid_ads,14.0,28,53.0,7.5,low,1,2025,False
2,2025-01-01,social_media,18.0,36,56.0,6.1,low,1,2025,False
3,2025-01-01,referral,30.0,70,88.0,7.5,low,1,2025,False
4,2025-01-01,email,12.0,33,53.0,3.8,low,1,2025,False

In [124]:
dau = df.groupby('date')['active_users'].sum().reset_index()
dau

          date  active_users
0   2025-01-01           242
1   2025-01-02           227
2   2025-01-03           184
3   2025-01-04           307
4   2025-01-05           344
..         ...           ...
450 2026-03-27          1195
451 2026-03-28          1263
452 2026-03-29          1355
453 2026-03-30          1486
454 2026-03-31          1116

[455 rows x 2 columns]

In [125]:
#1. DAU (Daily Active Users trend)
dau['growth_rate'] = dau['active_users'].pct_change()

In [126]:
#hansı günlərdə sürətli artım / düşüş var
dau

          date  active_users  growth_rate
0   2025-01-01           242          NaN
1   2025-01-02           227    -0.061983
2   2025-01-03           184    -0.189427
3   2025-01-04           307     0.668478
4   2025-01-05           344     0.120521
..         ...           ...          ...
450 2026-03-27          1195    -0.016461
451 2026-03-28          1263     0.056904
452 2026-03-29          1355     0.072842
453 2026-03-30          1486     0.096679
454 2026-03-31          1116    -0.248991

[455 rows x 3 columns]

In [127]:
#Ən sürətli artım günlərini tapaq
dau.sort_values(by='growth_rate', ascending=False).head(5)

          date  active_users  growth_rate
417 2026-02-22          1115     1.027273
304 2025-11-01          1852     0.915202
435 2026-03-12          1393     0.741250
70  2025-03-12           519     0.685065
3   2025-01-04           307     0.668478

In [128]:
#Araşdırılmalı günlər
# +20% və yuxarı artım
high_growth = dau[dau['growth_rate'] > 0.2]

# -20% və aşağı düşüş
high_drop = dau[dau['growth_rate'] < -0.2]

In [129]:
high_growth

          date  active_users  growth_rate
3   2025-01-04           307     0.668478
6   2025-01-07           432     0.636364
10  2025-01-11           451     0.249307
14  2025-01-15           407     0.267913
16  2025-01-17           394     0.304636
20  2025-01-21           386     0.349650
24  2025-01-25           375     0.512097
26  2025-01-27           384     0.271523
29  2025-01-30           451     0.209115
35  2025-02-05           458     0.542088
40  2025-02-10           430     0.207865
46  2025-02-16           363     0.201987
47  2025-02-17           453     0.247934
58  2025-02-28           462     0.462025
63  2025-03-05           455     0.311239
68  2025-03-10           597     0.613514
70  2025-03-12           519     0.685065
72  2025-03-14           570     0.241830
75  2025-03-17           571     0.214894
77  2025-03-19           515     0.223278
83  2025-03-25           591     0.268240
91  2025-04-02           546     0.263889
103 2025-04-14           577     0.287946
117 2025-04-28           692     0.346304
128 2025-05-09           679     0.290875
132 2025-05-13           666     0.538106
134 2025-05-15           788     0.340136
136 2025-05-17           663     0.201087
138 2025-05-19           663     0.232342
160 2025-06-10           663     0.236940
171 2025-06-21           645     0.223909
183 2025-07-03           701     0.283883
198 2025-07-18           734     0.276522
206 2025-07-26           787     0.347603
216 2025-08-05           817     0.266667
221 2025-08-10           669     0.220803
243 2025-09-01           755     0.348214
247 2025-09-05           957     0.203774
253 2025-09-11           766     0.229535
272 2025-09-30           997     0.308399
284 2025-10-12          1114     0.220153
290 2025-10-18          1024     0.245742
304 2025-11-01          1852     0.915202
333 2025-11-30          2028     0.272271
368 2026-01-04          1168     0.273719
374 2026-01-10          1310     0.298315
386 2026-01-22          1212     0.292111
389 2026-01-25          1279     0.288016
393 2026-01-29          1369     0.300095
398 2026-02-03          1401     0.392644
417 2026-02-22          1115     1.027273
422 2026-02-27          1380     0.343720
435 2026-03-12          1393     0.741250

In [130]:
#. Sessions per user --- 1 istifadəçi orta hesabla neçə sessiya edir
df['sessions_per_user'] = df['sessions'] / df['active_users']
df.head()

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile,month,year,is_outlier,sessions_per_user
0,2025-01-01,organic,37.0,75,140.0,8.9,medium,1,2025,False,1.866667
1,2025-01-01,paid_ads,14.0,28,53.0,7.5,low,1,2025,False,1.892857
2,2025-01-01,social_media,18.0,36,56.0,6.1,low,1,2025,False,1.555556
3,2025-01-01,referral,30.0,70,88.0,7.5,low,1,2025,False,1.257143
4,2025-01-01,email,12.0,33,53.0,3.8,low,1,2025,False,1.606061

In [131]:
channel_sessions_per_user = df.groupby('acquisition_channel')['sessions_per_user'].mean().reset_index()
print(channel_sessions_per_user)

  acquisition_channel  sessions_per_user
0               email           1.648886
1             organic           1.641754
2            paid_ads           1.562707
3            referral           1.672249
4        social_media           1.570682

/tmp/ipykernel_10612/1827232662.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  channel_sessions_per_user = df.groupby('acquisition_channel')['sessions_per_user'].mean().reset_index()

In [132]:
#Total engagement
df['total_time'] = df['sessions'] * df['avg_session_duration']

In [133]:
df.head()

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile,month,year,is_outlier,sessions_per_user,total_time
0,2025-01-01,organic,37.0,75,140.0,8.9,medium,1,2025,False,1.866667,1246.0
1,2025-01-01,paid_ads,14.0,28,53.0,7.5,low,1,2025,False,1.892857,397.5
2,2025-01-01,social_media,18.0,36,56.0,6.1,low,1,2025,False,1.555556,341.6
3,2025-01-01,referral,30.0,70,88.0,7.5,low,1,2025,False,1.257143,660.0
4,2025-01-01,email,12.0,33,53.0,3.8,low,1,2025,False,1.606061,201.4

In [134]:
#Kanal performansi
channel_perf = df.groupby('acquisition_channel').agg(
    total_time=('total_time', 'sum'),
    count=('date', 'count')
).reset_index()

channel_perf = channel_perf.sort_values(by='total_time', ascending=False)

channel_perf

/tmp/ipykernel_10612/2144028809.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  channel_perf = df.groupby('acquisition_channel').agg(

  acquisition_channel  total_time  count
1             organic   1482666.4    447
4        social_media    986401.4    464
2            paid_ads    941338.7    449
3            referral    515851.7    423
0               email    465899.6    421

In [135]:
#Heftenin gunleri uzre ortalama session
df['weekday'] = pd.to_datetime(df['date']).dt.day_name()

df.groupby('weekday')['sessions'].mean()

weekday
Friday       298.223301
Monday       309.619048
Saturday     292.249201
Sunday       293.493631
Thursday     282.921136
Tuesday      283.009404
Wednesday    277.160883
Name: sessions, dtype: float64

In [136]:
#Anomaly days
df[df['is_outlier'] == True]

,date,acquisition_channel,new_users,active_users,sessions,avg_session_duration,session_quantile,month,year,is_outlier,sessions_per_user,total_time,weekday
63,2025-01-13,referral,42.0,135,2210.0,8.8,high,1,2025,True,16.370370,19448.0,Monday
690,2025-05-19,organic,56.0,182,2460.0,5.1,high,5,2025,True,13.516484,12546.0,Monday
1140,2025-08-17,organic,35.0,113,1680.0,4.0,high,8,2025,True,14.867257,6720.0,Sunday
1148,2025-08-18,referral,29.0,65,1090.0,7.7,high,8,2025,True,16.769231,8393.0,Monday
1195,2025-08-28,organic,211.0,551,1007.0,9.3,high,8,2025,True,1.827586,9365.1,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,2026-03-20,organic,227.0,678,967.0,5.7,high,3,2026,True,1.426254,5511.9,Friday
2226,2026-03-22,paid_ads,237.0,736,885.0,5.2,high,3,2026,True,1.202446,4602.0,Sunday
2230,2026-03-23,organic,254.0,780,1313.0,7.1,high,3,2026,True,1.683333,9322.3,Monday
2242,2026-03-25,social_media,280.0,918,1242.0,3.9,high,3,2026,True,1.352941,4843.8,Wednesday
2270,2026-03-31,organic,274.0,613,757.0,5.1,high,3,2026,True,1.234910,3860.7,Tuesday

# Ən çox istifadəçi gətirən kanal ən effektiv kanal deyil — effektivlik istifadəçinin platformada keçirdiyi vaxt və aktivliklə ölçülməlidir.